export { ChangeManager } from './change-manager.js'
export type { SearchOptions, SearchResult } from './search-manager.js'
export { SearchManager } from './search-manager.js'
export type { InitializeOptions, UpdateOptions } from './workspace.js'
export { Workspace } from './workspace.js'
